/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as KarriereIndexRouteImport } from './routes/karriere.index'
import { Route as KarriereSlugRouteImport } from './routes/karriere.$slug'
import { Route as KarriereBewerbungRouteImport } from './routes/karriere.bewerbung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereIndexRoute = KarriereIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KarriereRoute,
} as any)
const KarriereSlugRoute = KarriereSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KarriereRoute,
} as any)
const KarriereBewerbungRoute = KarriereBewerbungRouteImport.update({
  id: '/bewerbung',
  path: '/bewerbung',
  getParentRoute: () => KarriereRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/unternehmen': typeof UnternehmenRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/karriere/': typeof KarriereIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/unternehmen': typeof UnternehmenRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/karriere': typeof KarriereIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/team': typeof TeamRoute
  '/unternehmen': typeof UnternehmenRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/karriere/': typeof KarriereIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/leistungen'
    | '/team'
    | '/unternehmen'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/karriere/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/team'
    | '/unternehmen'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/karriere'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/leistungen'
    | '/team'
    | '/unternehmen'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/karriere/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KarriereRoute: typeof KarriereRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  TeamRoute: typeof TeamRoute
  UnternehmenRoute: typeof UnternehmenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/': {
      id: '/karriere/'
      path: '/'
      fullPath: '/karriere/'
      preLoaderRoute: typeof KarriereIndexRouteImport
      parentRoute: typeof KarriereRoute
    }
    '/karriere/$slug': {
      id: '/karriere/$slug'
      path: '/$slug'
      fullPath: '/karriere/$slug'
      preLoaderRoute: typeof KarriereSlugRouteImport
      parentRoute: typeof KarriereRoute
    }
    '/karriere/bewerbung': {
      id: '/karriere/bewerbung'
      path: '/bewerbung'
      fullPath: '/karriere/bewerbung'
      preLoaderRoute: typeof KarriereBewerbungRouteImport
      parentRoute: typeof KarriereRoute
    }
  }
}

interface KarriereRouteChildren {
  KarriereSlugRoute: typeof KarriereSlugRoute
  KarriereBewerbungRoute: typeof KarriereBewerbungRoute
  KarriereIndexRoute: typeof KarriereIndexRoute
}

const KarriereRouteChildren: KarriereRouteChildren = {
  KarriereSlugRoute: KarriereSlugRoute,
  KarriereBewerbungRoute: KarriereBewerbungRoute,
  KarriereIndexRoute: KarriereIndexRoute,
}

const KarriereRouteWithChildren = KarriereRoute._addFileChildren(
  KarriereRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KarriereRoute: KarriereRouteWithChildren,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  TeamRoute: TeamRoute,
  UnternehmenRoute: UnternehmenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
